spring.application.name=OAuth2demo
spring.security.oauth2.client.registration.google.client-id=149620683782-4qsa8h5jvbrkagodukjmcr0g7fisv1j2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.github.client-id=Ov23lintvDfAImZzaEXb
spring.security.oauth2.client.registration.github.client-secret=6072af117c56b4a0210e2f684e84009c0d163196